<?php

$xmltxt = '<RESPUESTA>
  <IDTRAN>60748736</IDTRAN>
  <OPER>ELG</OPER>
  <FECHAOPER>2023-11-30</FECHAOPER>
  <STATUS>OK</STATUS>
  <RSPCODG>MSGXML_1000</RSPCODG>
  <RSPMSGG>AFILIACION  VALIDA</RSPMSGG>
  <AFICODIGO>341058/16</AFICODIGO>
  <AFIPLAN>AS300</AFIPLAN>
  <AFIAPE>MISKEVISH</AFIAPE>
  <AFINOM>FEDERICO</AFINOM>
  <AFISEXO>M</AFISEXO>
  <AFINAC>1995-10-05</AFINAC>
  <AFIAFIL>NO GRAVADO</AFIAFIL>
  <AFIDNI>-39249075</AFIDNI>
</RESPUESTA>
';

$x2 = '<RESPUESTA> <IDTRAN>60748736</IDTRAN> <OPER>ELG</OPER> <FECHAOPER>2023-11-30</FECHAOPER> <STATUS>OK</STATUS> <RSPCODG>MSGXML_1000</RSPCODG> <RSPMSGG>AFILIACION VALIDA</RSPMSGG> <AFICODIGO>341058/16</AFICODIGO> <AFIPLAN>AS300</AFIPLAN> <AFIAPE>MISKEVISH</AFIAPE> <AFINOM>FEDERICO</AFINOM> <AFISEXO>M</AFISEXO> <AFINAC>1995-10-05</AFINAC> <AFIAFIL>NO GRAVADO</AFIAFIL> <AFIDNI>-39249075</AFIDNI> </RESPUESTA>';

$xml = simplexml_load_string(trim($x2)) or die("Error: Cannot create object");
echo $xml->IDTRAN . "<br>";
//echo $xml->book[1]->title;
?>
